syntax = "proto3";

package robot;

message VelocityCommand {
    float vx_percent = 1; // strafe velocity
    float vy_percent = 2; // forward/backward velocity
    float omega_percent = 3;
}

message PoseCommand {
    float x_m = 1;
    float y_m = 2;
    float theta_rad = 3;
}

message TapeFollowCommand {
    float forward_speed_percent = 1;
}

message StopCommand {
    bool brake = 1;
}

message DriveCommand {
    uint32 sequence = 1;
    oneof command {
        VelocityCommand velocity = 2;
        TapeFollowCommand tape_follow = 3;
        PoseCommand pose = 4;
        StopCommand stop = 5;
    }
}
