[platformio]
default_envs = debug

[env]
platform = https://github.com/pioarduino/platform-espressif32.git
framework = arduino
board = esp32-s3-devkitm-1
lib_ldf_mode = deep+
monitor_speed = 115200
test_framework = unity

lib_deps = 
    AccelStepper

build_unflags =
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++2a
    -I include
    -D SERIAL_BAUD=${env.monitor_speed}

[env:debug]
build_type = debug
build_flags =
    ${env.build_flags}
    -DDEBUG
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG


[env:release]
build_type = release
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_WARN