[platformio]
default_envs =
    master_esp_debug
    drivetrain_esp_debug

[env]
platform = https://github.com/pioarduino/platform-espressif32.git
framework = arduino
board = esp32-s3-devkitm-1
lib_ldf_mode = deep+
monitor_speed = 115200
test_framework = unity

lib_deps =
    AccelStepper @ 1.64.0
    nanopb/Nanopb @ 0.4.9

custom_nanopb_protos =
    +<lib/comms/proto/*.proto>

custom_nanopb_options =
    --error-on-unmatched

build_unflags =
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++2a
    -I lib
    -D SERIAL_BAUD=${env.monitor_speed}

[env:master_esp_debug]
build_type = debug
build_src_filter =
    +<master_esp/**>
    -<drivetrain_esp/**>
build_flags =
    ${env.build_flags}
    -Iinclude/master_esp
    -DROBOT_MASTER_ESP
    -DDEBUG
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE


[env:drivetrain_esp_debug]
build_type = debug
build_src_filter =
    +<drivetrain_esp/**>
    -<master_esp/**>
build_flags =
    ${env.build_flags}
    -I include/drivetrain_esp
    -D ROBOT_DRIVETRAIN_ESP
    -D DEBUG
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE


[env:master_esp_release]
build_type = release
build_src_filter =
    +<master_esp/**>
    -<drivetrain_esp/**>
build_flags =
    ${env.build_flags}
    -I include/master_esp
    -D ROBOT_MASTER_ESP
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_WARN


[env:drivetrain_release]
build_src_filter =
    +<drivetrain_esp/**>
    -<master_esp/**>
build_flags =
    ${env.build_flags}
    -I include/drivetrain_esp
    -D ROBOT_DRIVETRAIN_ESP
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_WARN

